services:
  postgres:
    image: postgres
    volumes:
      - /postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: xlr8code
    ports:
      - 5432:5432
