spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:6543/xlr8code
    username: two-forty # example
    password: forty-two # example
    driverClassName: org.postgresql.Driver

jwt:
  access-token:
    secret-key: secret
    expiration-time: 15
    unit: MINUTES
  refresh-token:
    expiration-time: 7
    unit: DAYS

user:
  activation-code:
    unit: HOURS
    expiration-time: 15
  password-reset-code:
    unit: MINUTES
    expiration-time: 15