spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: validate
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:6543/xlr8code
    username: two-forty
    password: forty-two
    driverClassName: org.postgresql.Driver

  flyway:
    locations: classpath:db/migration