spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://test:0000/test
    username: test
    password: test
    driverClassName: org.postgresql.Driver

user:
  session:
    expiration-time: 7
    unit: DAYS
    token-length: 64
    key: fake-secret-dont-use-this
  activation-code:
    unit: HOURS
    expiration-time: 15
    length: 6
  password-reset-code:
    unit: MINUTES
    expiration-time: 15
    length: 6

authentication:
  cleanup-cron: 0 0 0 * * * # every day at midnight

logging:
  config: classpath:log4j2.xml