spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:6543/xlr8code
    username: two-forty
    password: forty-two
    driverClassName: org.postgresql.Driver

jwt:
  secret-key: secret
  access-expiration-time: 15 # minutes
  refresh-expiration-time: 30 # days

logging:
  level:
    org:
      springframework:
        transaction:
          interceptor:
            TRACE
