spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:6543/xlr8code
    username: two-forty
    password: forty-two
    driverClassName: org.postgresql.Driver

jwt:
  access-token:
    secret-key: secret
    expiration-time: 15
    unit: MINUTES
  refresh-token:
    expiration-time: 7
    unit: DAYS

logging:
  level:
    org:
      springframework:
        transaction:
          interceptor:
            TRACE
