spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/xlr8code
    username: two-forty
    password: forty-two
    driverClassName: org.postgresql.Driver
