name: 'Build application'
on:
  workflow_dispatch:

jobs:
  build-backend:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: 'maven'

      - name: Setup Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: '3.9.8'

      - name: Build with Maven
        working-directory: server 
        run: mvn -B package --file pom.xml -DskipTests 

      - name: Extract project version from pom.xml
        id: extract-version
        run: echo ::set-output name=version::$(mvn -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive exec:exec)
        working-directory: server

      - name: Login to DockerHub
        id: docker-login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: extract-metadata
        uses: docker/metadata-action@v5
        with:
          images: guiraldelli/xlr8server
          tags: ${{ steps.extract-version.outputs.version }}, latest

      - name: Build and push Docker image
        id: docker-build
        uses: docker/build-push-action@v2
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: | 
            ${{ secrets.DOCKER_USERNAME }}/xlr8server:${{ steps.extract-version.outputs.version }}
            ${{ secrets.DOCKER_USERNAME }}/xlr8server:latest
      - name: Clean docker images
        run: docker image prune -f

  restart-container:
    runs-on: self-hosted
    needs: build-backend
    steps:
      - name: Pull new images
        run: docker compose -f ~/xlr8code/compose.yaml pull
        
      - name: Restart containers
        run: docker compose -f ~/xlr8code/compose.yaml up -d