name: 'Build application'
on:
  release: 
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v4
      - name: Set up GraalVM
        id: graalvm
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: 21
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build native image
        id: native-image
        run: 'mvnw package -Pnative'
        working-directory: 'server'
      - name: Login to DockerHub
        id: docker-login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: extract-metadata
        uses: docker/metadata-action@v5
        with:
          images: guiraldellis/xlr8server
          tags: 'latest'
      - name: Build and push Docker image
        id: docker-build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./server/Dockerfile
          push: true
          tags: ${{ steps.extract-metadata.outputs.tags }}