name: 'Build application'
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: 'maven'
      - name: Build with Maven
        working-directory: server
        run: mvnw -B package --file pom.xml -DskipTests
      - name: Extract project version from pom.xml
        id: extract-version
        run: echo ::set-output name=version::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
      - name: Login to DockerHub
        id: docker-login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: extract-metadata
        uses: docker/metadata-action@v5
        with:
          images: guiraldellis/xlr8server
          tags: ${{ steps.extract-version.outputs.version }}
      - name: Build and push Docker image
        id: docker-build
        uses: docker/build-push-action@v2
        with:
          file: ./server/Dockerfile
          push: true
          tags: ${{ steps.extract-metadata.outputs.tags }}